version: '3'

services:
  app:
    restart: always
    container_name: kelompok5
    environment:
      - TZ=Asia/Makassar
    build:
      context: .
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8002 --workers 2